name: ABCSwift
schemes:
  ABCSwift:
    build:
      targets:
        ABCSwift: run
    run:
      config:Debug
    test:
      config:Debug
    profile:
      config:Debug
    analyze:
      config:Debug
    archive:
      config:Debug
targets:
  ABCSwift:
    type: tool
    platform: macOS
    sources:
      - ABCSwift
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.sshayashi.ABCSwift
